# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class QLabelClickable(QtWidgets.QLabel):
    clicked = QtCore.pyqtSignal(str)
    def __init__(self,parent=None):
        super(QLabelClickable,self).__init__(parent)
    def mousePressEvent(self,event):
        self.action = "click"
    def mouseReleaseEvent(self,event):
        if self.action == "click":
            self.clicked.emit(self.action)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 444)
        Form.setStyleSheet("    background-color: #fff;")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 100, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
"color: #454544;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: transparent;\n"
"color: #454544;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(25, 200, 90, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: transparent;\n"
"color: #454544;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(110, 160, 231, 25))
        self.lineEdit_email.setStyleSheet("background-color: #c2c7d5;\n"
"color: #2a547f;\n"
"border: none;\n"
"padding: 5px;")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(110, 200, 231, 25))
        self.lineEdit_password.setStyleSheet("background-color: #c2c7d5;\n"
"color: #2a547f;\n"
"border: none;\n"
"padding: 5px;")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.welcome_label = QtWidgets.QLabel(Form)
        self.welcome_label.setGeometry(QtCore.QRect(10, 15, 400, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(26)
        font.setBold(True)
        self.welcome_label.setFont(font)
        self.welcome_label.setStyleSheet("background-color: transparent;\n"
"color: #454544;\n"
"font-weight: bold;\n"
"\n"
"")
        self.welcome_label.setObjectName("welcome_label")
        self.login_btn = QtWidgets.QPushButton(Form)
        self.login_btn.setGeometry(QtCore.QRect(140, 250, 130, 54))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        font.setBold(True)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #5c5c5c;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #5564f2;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3d4ef2;\n"
"\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(120, 310, 120, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: transparent;\n"
"color: #454544;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_register = QLabelClickable(Form)
        self.label_register.setGeometry(QtCore.QRect(240, 310, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        self.label_register.setFont(font)
        self.label_register.setStyleSheet("background-color: transparent;\n"
"color: #454544;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label_register.setCursor(QCursor(Qt.PointingHandCursor))
        self.label_register.setObjectName("label_register")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BookIt"))
        self.label.setText(_translate("Form", "Login"))
        self.label_2.setText(_translate("Form", "Email:"))
        self.label_3.setText(_translate("Form", "Password:"))
        self.welcome_label.setText(_translate("Form", "Welcome To BookIt"))
        self.login_btn.setText(_translate("Form", "Log In"))
        self.label_4.setText(_translate("Form", "Not a member?"))
        self.label_register.setText(_translate("Form", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
