# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setAccessibleName("")
        MainWindow.setStyleSheet("background-color: #fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mange_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mange_btn.setGeometry(QtCore.QRect(20, 100, 371, 171))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(28)
        font.setBold(True)
        self.mange_btn.setFont(font)
        self.mange_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #5c5c5c;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #5564f2;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3d4ef2;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("manage.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mange_btn.setIcon(icon)
        self.mange_btn.setIconSize(QtCore.QSize(350, 171))
        self.mange_btn.setObjectName("mange_btn")
        self.unlock_btn = QtWidgets.QPushButton(self.centralwidget)
        self.unlock_btn.setGeometry(QtCore.QRect(20, 300, 371, 171))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(28)
        font.setBold(True)
        self.unlock_btn.setFont(font)
        self.unlock_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #5c5c5c;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #5564f2;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3d4ef2;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("unlock.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unlock_btn.setIcon(icon1)
        self.unlock_btn.setIconSize(QtCore.QSize(371, 171))
        self.unlock_btn.setObjectName("unlock_btn")
        self.menu_label = QtWidgets.QLabel(self.centralwidget)
        self.menu_label.setGeometry(QtCore.QRect(120, 10, 155, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(38)
        font.setBold(True)
        self.menu_label.setFont(font)
        self.menu_label.setStyleSheet("    background-color: transparent;\n"
"    color: #454544;\n"
"    font-weight: bold;")
        self.menu_label.setObjectName("menu_label")

        self.logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.logout_btn.setGeometry(QtCore.QRect(300, 10, 90, 45))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        font.setBold(True)
        self.logout_btn.setFont(font)
        self.logout_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #e58c1f;\n"
"    color: #fff;\n"
"    border-top-right-radius: 16px;\n"
"    border-top-left-radius: 16px;\n"
"    border-bottom-right-radius: 16px;\n"
"    border-bottom-left-radius: 16px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #5c5c5c;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #ff9c22;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #d3811c;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.logout_btn.setObjectName("logout_btn")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BookIt"))
        self.mange_btn.setText(_translate("MainWindow", ""))
        self.logout_btn.setText(_translate("MainWindow", "Logout"))
        self.unlock_btn.setText(_translate("MainWindow", ""))
        self.menu_label.setText(_translate("MainWindow", "Menu"))
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
