# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 444)
        Form.setStyleSheet("    background-color: #fff;")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(120, 110, 241, 22))
        self.lineEdit_email.setStyleSheet("background-color: #c2c7d5;\n"
"color: #2a547f;\n"
"border: none;\n"
"padding: 5px;\n"
"")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_firstname = QtWidgets.QLineEdit(Form)
        self.lineEdit_firstname.setGeometry(QtCore.QRect(120, 140, 241, 22))
        self.lineEdit_firstname.setStyleSheet("background-color: #c2c7d5;\n"
"color: #2a547f;\n"
"border: none;\n"
"padding: 5px;\n"
"")
        self.lineEdit_firstname.setObjectName("lineEdit_firstname")
        self.lineEdit_lastname = QtWidgets.QLineEdit(Form)
        self.lineEdit_lastname.setGeometry(QtCore.QRect(120, 170, 241, 22))
        self.lineEdit_lastname.setStyleSheet("background-color: #c2c7d5;\n"
"color: #2a547f;\n"
"border: none;\n"
"padding: 5px;\n"
"")
        self.lineEdit_lastname.setObjectName("lineEdit_lastname")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(120, 200, 241, 22))
        self.lineEdit_password.setStyleSheet("background-color: #c2c7d5;\n"
"color: #2a547f;\n"
"border: none;\n"
"padding: 5px;\n"
"")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_confirm_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_confirm_password.setGeometry(QtCore.QRect(160, 230, 201, 22))
        self.lineEdit_confirm_password.setStyleSheet("background-color: #c2c7d5;\n"
"color: #2a547f;\n"
"border: none;\n"
"padding: 5px;\n"
"")
        self.lineEdit_confirm_password.setObjectName("lineEdit_confirm_password")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 110, 50, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        # font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("    background-color: transparent;\n"
"    color: #454544;\n"
"    font-weight: bold;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 100, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("    background-color: transparent;\n"
"    color: #454544;\n"
"    font-weight: bold;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(51, 170, 100, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        # font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("    background-color: transparent;\n"
"    color: #454544;\n"
"    font-weight: bold;\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(55, 200, 90, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        # font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("    background-color: transparent;\n"
"    color: #454544;\n"
"    font-weight: bold;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(45, 230, 170, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        # font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("    background-color: transparent;\n"
"    color: #454544;\n"
"    font-weight: bold;\n"
"")
        self.label_7.setObjectName("label_7")
        self.registerBtn = QtWidgets.QPushButton(Form)
        self.registerBtn.setGeometry(QtCore.QRect(140, 280, 140, 55))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        # font.setBold(True)
        self.registerBtn.setFont(font)
        self.registerBtn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #5c5c5c;\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #5564f2;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3d4ef2;\n"
"\n"
"}")
        self.registerBtn.setObjectName("registerBtn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 20, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(36)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("    background-color: transparent;\n"
"    color: #454544;\n"
"    font-weight: bold;\n"
"")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BookIt"))
        self.label_3.setText(_translate("Form", "Email:"))
        self.label_4.setText(_translate("Form", "First Name:"))
        self.label_5.setText(_translate("Form", "Last Name:"))
        self.label_6.setText(_translate("Form", "Password:"))
        self.label_7.setText(_translate("Form", "Confirm Password:"))
        self.registerBtn.setText(_translate("Form", "Register"))
        self.label.setText(_translate("Form", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
