# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QrDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *

class Ui_Dialog(object):
    def __init__(self,flag=False):
        self.flag = flag
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 250)
        Dialog.setStyleSheet("background-color: #fff;")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(225, 100, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(21)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: transparent;\n"
"color: #454544;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.image_label = QtWidgets.QLabel(Dialog)
        self.image_label.setGeometry(QtCore.QRect(0, 0, 213, 250))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        if self.flag ==True:
            self.image_label.setPixmap(QPixmap("QR_CODE.PNG"))
            self.image_label.setScaledContents(True)
        else:
            self.image_label.setPixmap(QPixmap("correct.PNG"))
            self.image_label.setScaledContents(True)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BookIt"))
        self.label_2.setText(_translate("Dialog", "Your Action Complete!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
